# Generated by Django 3.0.3 on 2020-05-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carseat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='productID',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
