# Generated by Django 3.0.3 on 2020-05-28 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carseat', '0002_auto_20200528_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
    ]
