# Generated by Django 3.0.3 on 2020-05-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carseat', '0003_remove_customer_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('safety', models.CharField(max_length=200, null=True)),
                ('temperature', models.CharField(max_length=200, null=True)),
                ('longitude', models.CharField(max_length=200, null=True)),
                ('latitude', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
