# Generated by Django 3.0.3 on 2020-05-28 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carseat', '0004_sensor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sensor',
        ),
    ]
