# Generated by Django 3.0.3 on 2020-05-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carseat', '0005_delete_sensor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firebase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
