# Generated by Django 3.0.3 on 2020-05-28 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carseat', '0006_firebase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Firebase',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='email',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='long',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='date_created',
            new_name='safe',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='productID',
            new_name='temp',
        ),
    ]
